gcc-c++11-Qt5:
  variables:     
    COMPILER:       "gcc"     
    LANGUAGE:       "C++11"     
    QTVERSION:      "QT5"     
    GIT_SUBMODULE_STRATEGY: recursive
  script: "CI/ci-linux.sh"
  tags:
    - Linux

gcc-c++11-Qt5.9.0:
  variables:     
    COMPILER:       "gcc"     
    LANGUAGE:       "C++11"     
    QTVERSION:      "QT5.9.0"     
    GIT_SUBMODULE_STRATEGY: recursive
  script: "CI/ci-linux.sh"
  tags:
    - Linux

clang-c++11-Qt5:
  variables:
    COMPILER:       "clang"     
    LANGUAGE:       "C++11"   
    QTVERSION:      "QT5"     
    GIT_SUBMODULE_STRATEGY: recursive
  script: "CI/ci-linux.sh"
  tags:
    - Linux
    - MultiThreads

clang-c++11-Qt5.9.0:
  variables:
    COMPILER:       "clang"     
    LANGUAGE:       "C++11"   
    QTVERSION:      "QT5.9.0"     
    GIT_SUBMODULE_STRATEGY: recursive
  script: "CI/ci-linux.sh"
  tags:
    - Linux
    - MultiThreads


cppcheck:
  script: "CI/ci-cppcheck.sh"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - Linux
    - MultiThreads
  artifacts:
    paths:
      - cppcheck.log

VS2015-Qt-5.6.2-x64:
  script: "CI\\ci-windows.bat"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
     ARCHITECTURE: "x64"
     QT_VERSION: "Qt5.6.2"
     COMPILER: "VS2015"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe

VS2015-Qt-5.6.2-x32:
  script: "CI\\ci-windows.bat"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    ARCHITECTURE: "x32"
    QT_VERSION: "Qt5.6.2"
    COMPILER: "VS2015"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe

VS2015-Qt-5.9.0-x64:
  script: "CI\\ci-windows.bat"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
     ARCHITECTURE: "x64"
     QT_VERSION: "Qt5.9.0"
     COMPILER: "VS2015"
  tags: 
    - VS2015
  artifacts:
    paths:
      - rel/*.exe

VS2015-Qt-5.9.0-x32:
  script: "CI\\ci-windows.bat"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    ARCHITECTURE: "x32"
    QT_VERSION: "Qt5.9.0"
    COMPILER: "VS2015"
  tags: 
    - VS2015
  artifacts:
    paths:
      - rel/*.exe

VS2013-Qt-5.5.1-x64:
  script: "CI\\ci-windows.bat"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
     ARCHITECTURE: "x64"
     QT_VERSION: "Qt5.5.1"
     COMPILER: "VS2013"
  tags:
    - VS2013
    - Qt551
  artifacts:
    paths:
      - rel/*.exe

INTEL-Qt-5.5.1-x64:
  script: "CI\\ci-windows.bat"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
     ARCHITECTURE: "x64"
     QT_VERSION: "Qt5.5.1"
     COMPILER: "VS2013"
     TOOLSET: "intel"
  tags:
    - VS2013
    - Qt551
  artifacts:
    paths:
      - rel/*.exe

Mac-Cpp11:
  script: "CI/ci-mac.sh"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - Apple
  artifacts:
    paths:
      - build-release/*.dmg

Doc-publish:
  only:
     - master
  script: "CI/ci-doc.sh"
  tags:
     - Linux
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
       - build-release/Doxygen-warning.log 
       - build-release/Doxygen-error.log




