gcc-c++11-Qt5:
  variables:     
    COMPILER:       "gcc"     
    LANGUAGE:       "C++11"     
    QTVERSION:      "QT5"     
  script: " git submodule update --init --remote ; OpenFlipper/CI/ci-linux.sh"
  tags:
    - Linux

clang-c++11-Qt5:
  variables:
    COMPILER:       "clang"     
    LANGUAGE:       "C++11"   
    QTVERSION:      "QT5"     
  script: " git submodule update --init --remote ; OpenFlipper/CI/ci-linux.sh"
  tags:
    - Linux
    - MultiThreads

cppcheck:
  script: " git submodule update --init --remote ; OpenFlipper/CI/ci-cppcheck.sh"
  tags:
    - Linux
    - MultiThreads
  artifacts:
    paths:
      - cppcheck.log

VS2015-Qt-5.6.0-x64:
  script: "OpenFlipper\\CI\\VS2015-Qt-5.6.0-x64.bat"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe

VS2015-Qt-5.6.0-x32:
  script: "OpenFlipper\\CI\\VS2015-Qt-5.6.0-x32.bat"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe


VS2013-Qt-5.5.1-x64:
  script: "OpenFlipper\\CI\\VS2013-Qt-5.5.1-x64.bat"
  tags:
    - VS2013
    - Qt551
  artifacts:
    paths:
      - rel/*.exe

Mac-Cpp11:
  script: " git submodule update --init --remote ; OpenFlipper/CI/ci-mac.sh"
  tags:
    - Apple
  artifacts:
    paths:
      - build-release/*.dmg

Doc-publish:
  only:
     - master
  script: " git submodule update --init --remote ; OpenFlipper/CI/ci-doc.sh"
  tags:
     - Linux
  artifacts:
    paths:
       - build-release/Doxygen-warning.log 
       - build-release/Doxygen-error.log




