gcc-c++11-Qt5:
  script: "CI/ci-linux.sh gcc C++11 QT5"
  tags:
    - Linux

clang-c++11-Qt5:
  script: "CI/ci-linux.sh clang C++11 QT5"
  tags:
    - Linux
    - MultiThreads

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
    - MultiThreads
  artifacts:
    paths:
      - cppcheck.log

VS2015-Qt-5.6.0-x64:
  script: "JI\\Configure-VS2015-Qt-5.6.0-x64.bat & JI\\Build-VS2015-Qt-5.6.0-x64.bat & JI\\Test-VS2015-Qt-5.6.0-x64.bat & JI\\Package-VS2015-Qt-5.6.0-x64.bat"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe
