gcc-c++11-Qt5:
  script: "OpenFlipper/CI/ci-linux.sh gcc C++11 QT5"
  tags:
    - Linux

clang-c++11-Qt5:
  script: "OpenFlipper/CI/ci-linux.sh clang C++11 QT5"
  tags:
    - Linux
    - MultiThreads

cppcheck:
  script: "OpenFlipper/CI/ci-cppcheck.sh"
  tags:
    - Linux
    - MultiThreads
  artifacts:
    paths:
      - cppcheck.log

VS2015-Qt-5.6.0-x64:
  script: "OpenFlipper\\CI\\VS2015-Qt-5.6.0-x64.bat"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe

VS2015-Qt-5.6.0-x32:
  script: "OpenFlipper\\CI\\VS2015-Qt-5.6.0-x32.bat"
  tags: 
    - VS2015
    - Qt56
  artifacts:
    paths:
      - rel/*.exe


VS2013-Qt-5.5.1-x64:
  script: "OpenFlipper\\CI\\VS2013-Qt-5.5.1-x64.bat"
  tags:
    - VS2013
    - Qt551
  artifacts:
    paths:
      - rel/*.exe

Mac-Cpp11:
  script: "OpenFlipper/CI/ci-mac.sh"
  cache:
    paths:
      - build-release/
  tags:
    - Apple
  artifacts:
    paths:
      - build-release/*.dmg
