gcc-c++11-Qt5:
  script: "CI/ci-linux.sh gcc C++11 QT5"
  tags:
    - Linux

clang-c++11-Qt5:
  script: "CI/ci-linux.sh clang C++11 QT5"
  tags:
    - Linux
    - MultiThreads

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
    - MultiThreads
  artifacts:
    paths:
      - cppcheck.log
