set (MSVC_GROUPING ON CACHE BOOL "Group Files by folder structure on MSVC.")
MACRO (RECURSE_GROUPS dirname)
if(${MSVC_GROUPING})
     SET(ALL_FILES)
     FILE(GLOB_RECURSE allfiles "${dirname}/*.*")
     SET(ALL_FILES ${ALL_FILES} ${allfiles})
     STRING(REGEX REPLACE ".*/([^/]*)" "\\1" maindir "${dirname}")

     FOREACH(file ${allfiles})
         STRING(REGEX REPLACE "${dirname}/(.*)/[^/]*" "\\1" loopdirname "${file}")
         STRING(REGEX REPLACE "/" "\\\\" loopdirname "${loopdirname}")

         IF(NOT "${file}" MATCHES "${dirname}/(.*)/[^/]*")
             source_group("${maindir}" FILES  ${file})
         ELSE()
             source_group("${maindir}\\${loopdirname}" FILES ${file})
         ENDIF()
     ENDFOREACH()
endif(${MSVC_GROUPING})
ENDMACRO (RECURSE_GROUPS)